collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6607000625226647
  brandStrength: 0.9184385936241597
  rhythmicContrast: 0.3822854880709201
  brandColors:
    - '#3E454C'
    - '#2185C5'
    - '#7ECEFD'
    - '#FFF6E5'
    - '#FF7F66'
  lightness: 0.4944837032817304
typography_spectrum: 0.3216971
layout_spectrum: 0.5418904
name: Joe Gilkey
